Repository ambitus/pyracf, pull requests merged in 2023-11, with the labels that each got.

#29 Resource profile sub functions
  pyracf/common/irrsmo00.c
  pyracf/data_set/data_set_admin.py
  pyracf/group/group_admin.py
  pyracf/resource/resource_admin.py
  tests/data_set/test_data_set_result_parser.py
  tests/resource/resource_request_samples/add_appc_session_request.xml
  tests/resource/resource_request_samples/add_custom_field_request.xml
  tests/resource/resource_request_samples/add_kerberos_realm_request.xml
  tests/resource/resource_request_samples/add_resource_class_request.xml
  tests/resource/resource_request_samples/add_signed_program_request.xml
  tests/resource/resource_request_samples/add_started_task_request.xml
  tests/resource/resource_request_samples/alter_appc_session_request.xml
  tests/resource/resource_request_samples/alter_custom_field_request.xml
  tests/resource/resource_request_samples/alter_kerberos_realm_request.xml
  tests/resource/resource_request_samples/alter_resource_class_request.xml
  tests/resource/resource_request_samples/alter_signed_program_request.xml
  tests/resource/resource_request_samples/alter_started_task_request.xml
  tests/resource/resource_request_samples/delete_appc_session_request.xml
  tests/resource/resource_request_samples/delete_custom_field_request.xml
  tests/resource/resource_request_samples/delete_kerberos_realm_request.xml
  tests/resource/resource_request_samples/delete_resource_class_request.xml
  tests/resource/resource_request_samples/delete_signed_program_request.xml
  tests/resource/resource_request_samples/delete_started_task_request.xml
  tests/resource/resource_result_samples/extract_resource_result_base_cdtinfo_error.xml
  tests/resource/resource_result_samples/extract_resource_result_base_cdtinfo_success.xml
  tests/resource/resource_result_samples/extract_resource_result_base_cfdef_error.xml
  tests/resource/resource_result_samples/extract_resource_result_base_cfdef_success.xml
  tests/resource/resource_result_samples/extract_resource_result_base_generic_success.xml
  tests/resource/resource_result_samples/extract_resource_result_base_kerb_error.xml
  tests/resource/resource_result_samples/extract_resource_result_base_kerb_success.xml
  tests/resource/resource_result_samples/extract_resource_result_base_session_error.xml
  tests/resource/resource_result_samples/extract_resource_result_base_session_success.xml
  tests/resource/resource_result_samples/extract_resource_result_base_sigver_error.xml
  tests/resource/resource_result_samples/extract_resource_result_base_sigver_success.xml
  tests/resource/resource_result_samples/extract_resource_result_base_stdata_error.xml
  tests/resource/resource_result_samples/extract_resource_result_base_stdata_success.xml
  tests/resource/test_resource_constants.py
  tests/resource/test_resource_result_parser.py
  tests/resource/test_resource_subfunction_extracts.py
  tests/resource/test_resource_subfunction_requests.py
  tests/test_runner.py
Labels: enhancement

#31 Bug/filter out tso messages on success
  pyracf/common/irrsmo00.c
  pyracf/common/security_result.py
  tests/user/test_user_constants.py
  tests/user/test_user_debug_logging.py
  tests/user/test_user_result_parser.py
  tests/user/user_result_samples/extract_user_result_extra_messages_success.json
  tests/user/user_result_samples/extract_user_result_extra_messages_success.xml
Labels: bug

#34 Clear State before raising errors
  pyracf/access/access_admin.py
  pyracf/common/security_admin.py
  pyracf/connection/connection_admin.py
  pyracf/data_set/data_set_admin.py
  pyracf/group/group_admin.py
  pyracf/resource/resource_admin.py
  pyracf/setropts/setropts_admin.py
  pyracf/user/user_admin.py
  tests/user/test_user_request_builder.py
Labels: bug

#38 Bug/resource admin fixes
  pyracf/common/security_admin.py
  pyracf/resource/resource_admin.py
  pyracf/setropts/setropts_admin.py
  tests/resource/resource_result_samples/extract_resource_result_base_session_success.xml
  tests/resource/test_resource_constants.py
  tests/setropts/setropts_log_samples/list_setropts_success.log
  tests/setropts/setropts_log_samples/list_setropts_success_2.log
  tests/setropts/setropts_log_samples/list_setropts_success_3.log
  tests/setropts/setropts_result_samples/list_setropts_result_success.json
  tests/setropts/setropts_result_samples/list_setropts_result_success_2.json
  tests/setropts/setropts_result_samples/list_setropts_result_success_3.json
Labels: bug, enhancement

#39 Gh pages bug/resource admin fixes
  .gitignore
  resource/base/segments_traits_operators.md
  resource/subfunctions/appc_session.md
  resource/subfunctions/kerberos_realm.md
  resource/subfunctions/resource_class.md
  resource/subfunctions/started_task.md
  setropts/base/list_racf_options.md
Labels: bug, documentation

#42 Release 1.0b2
  .gitignore
  resource/base/segments_traits_operators.md
  resource/subfunctions/appc_session.md
  resource/subfunctions/kerberos_realm.md
  resource/subfunctions/resource_class.md
  resource/subfunctions/started_task.md
  setropts/base/list_racf_options.md
Labels: documentation

#41 Release 1.0b2
  pyracf/common/security_admin.py
  pyracf/resource/resource_admin.py
  pyracf/setropts/setropts_admin.py
  tests/resource/resource_result_samples/extract_resource_result_base_session_success.xml
  tests/resource/test_resource_constants.py
  tests/setropts/setropts_log_samples/list_setropts_success.log
  tests/setropts/setropts_log_samples/list_setropts_success_2.log
  tests/setropts/setropts_log_samples/list_setropts_success_3.log
  tests/setropts/setropts_result_samples/list_setropts_result_success.json
  tests/setropts/setropts_result_samples/list_setropts_result_success_2.json
  tests/setropts/setropts_result_samples/list_setropts_result_success_3.json
Labels: bug
