Repository ambitus/pyracf, pull requests merged in 2024-01, with the labels that each got.

#64 Gh pages feature/add optional expired
  user/abstractions/passphrase.md
  user/abstractions/password.md
Labels: documentation, enhancement

#51 Bug/resource extract auditing
  pyproject.toml
  pyracf/common/security_admin.py
  pyracf/resource/resource_admin.py
  tests/resource/resource_log_samples/alter_resource_error.log
  tests/resource/resource_log_samples/alter_resource_success.log
  tests/resource/resource_log_samples/extract_resource_base_success.log
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_access_level.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_access_level_all.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_access_level_multiple.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_access_level_none.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_attempt.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_attempt_all.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_attempt_multiple.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_attempt_none.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_access_level.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_access_level_all.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_access_level_multiple.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_access_level_none.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_attempt.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_attempt_all.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_attempt_multiple.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_attempt_none.xml
  tests/resource/resource_request_samples/resource_remove_all_audit_rules.xml
  tests/resource/resource_result_samples/extract_resource_result_base_success.json
  tests/resource/resource_result_samples/extract_resource_result_base_success.xml
  tests/resource/test_resource_constants.py
  tests/resource/test_resource_getters.py
  tests/resource/test_resource_setters.py
  tests/user/test_user_request_builder.py
Labels: bug, enhancement

#52 Add Documentation for New Audit Rules Functions
  resource/abstractions/auditing_rules.md
  resource/base/segments_traits_operators.md
Labels: documentation

#65 Release 1.0b4
  pyproject.toml
  pyracf/common/security_admin.py
  pyracf/data_set/data_set_admin.py
  pyracf/group/group_admin.py
  pyracf/resource/resource_admin.py
  pyracf/user/user_admin.py
  tests/resource/resource_log_samples/alter_resource_error.log
  tests/resource/resource_log_samples/alter_resource_success.log
  tests/resource/resource_log_samples/extract_resource_base_success.log
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_access_level.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_access_level_all.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_access_level_multiple.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_access_level_none.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_attempt.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_attempt_all.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_attempt_multiple.xml
  tests/resource/resource_request_samples/resource_alter_audit_rules_by_attempt_none.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_access_level.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_access_level_all.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_access_level_multiple.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_access_level_none.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_attempt.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_attempt_all.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_attempt_multiple.xml
  tests/resource/resource_request_samples/resource_overwrite_audit_rules_by_attempt_none.xml
  tests/resource/resource_request_samples/resource_remove_all_audit_rules.xml
  tests/resource/resource_result_samples/extract_resource_result_base_success.json
  tests/resource/resource_result_samples/extract_resource_result_base_success.xml
  tests/resource/test_resource_constants.py
  tests/resource/test_resource_getters.py
  tests/resource/test_resource_setters.py
  tests/user/test_user_constants.py
  tests/user/test_user_request_builder.py
  tests/user/test_user_setters.py
  tests/user/user_request_samples/user_set_passphrase_expired_request.xml
  tests/user/user_request_samples/user_set_passphrase_noexpired_request.xml
  tests/user/user_request_samples/user_set_password_expired_request.xml
  tests/user/user_request_samples/user_set_password_noexpired_request.xml
Labels: bug, enhancement

#66 Release 1.0b4
  resource/abstractions/auditing_rules.md
  resource/base/segments_traits_operators.md
  user/abstractions/passphrase.md
  user/abstractions/password.md
Labels: documentation
